PrdDeployer/PrdDeployer/urls.py
"""
Definition of urls for PrdDeployer.
"""

from django.conf.urls import include, url
from django.http import HttpResponseRedirect

import updateplanmgr.urls
import awsresourcemgr.urls
import ec2mgr.urls

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from django.contrib.auth.views import login, logout
admin.autodiscover()

urlpatterns = [
    # Examples:
    # url(r'^$', 'PrdDeployer.views.home', name='home'),
    # url(r'^PrdDeployer/', include('PrdDeployer.PrdDeployer.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^prdbsxt/admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^prdbsxt/admin/', include(admin.site.urls)),

    # updateplanmgr
    url(r'^prdbsxt/update/', include(updateplanmgr.urls, namespace='updateplanmgr', app_name='updateplanmgr')),
    # awsresourcemgr:
    url(r'^prdbsxt/awsres/', include(awsresourcemgr.urls, namespace='awsresourcemgr', app_name='awsresourcemgr')),
    # ec2mgr:
    url(r'^prdbsxt/ec2/', include(ec2mgr.urls, namespace='ec2mgr', app_name='ec2mgr')),

    url(r'^prdbsxt/accounts/login/', login,
        {'template_name': 'admin/login.html'}),
    url(r'^prdbsxt/accounts/logout/', logout, name='logout'),

    # Redirect any other requests to home page:
    url(r'^prdbsxt/$', lambda r: HttpResponseRedirect('update/'), name="home"),
    url(r'^$', lambda r: HttpResponseRedirect('prdbsxt/update/'), name="home"),
    #url(r'^/$', lambda r: HttpResponseRedirect('prdbsxt/update/'), name="home"),
]

PrdDeployer/awsresourcemgr/urls.py
from django.conf.urls import include, url

from awsresourcemgr import views

urlpatterns = [
    url(
        r'update_resources/(?P<profile_name>[a-zA-Z0-9-]+)/(?P<region_name>[a-zA-Z0-9-]+)/(?P<resource_type>.+)/$',
        views.update_resources,
        name="update_resources"
    ),
    url(
        r'resources/(?P<profile_name>[a-zA-Z0-9-]+)/(?P<region_name>[a-zA-Z0-9-]+)/$',
        views.resources,
        name="resources"
    ),
]

PrdDeployer/ec2mgr/urls.py
from django.conf.urls import include, url

from ec2mgr import views

urlpatterns = [
    url(r'^sync/(?P<profile_name>[a-zA-Z0-9-]+)/(?P<region_name>[a-zA-Z0-9-]+)/$', views.sync_instances_ex, name="sync_instances_ex"),
    url(r'instances/', views.instances, name="instances"),
    url(r'retired/', views.retired_instances, name='retired_instances'),
]

PrdDeployer/updateplanmgr/urls.py
from django.conf.urls import include, url

from updateplanmgr import views
from updateplanmgr import ajax_views
from updateplanmgr import api_views

urlpatterns = [
    #url(r'^v1/$', views.v1),
    #url(r'^v2/(?P<profile_name>[a-zA-Z0-9-]+)/(?P<region_name>[a-zA-Z0-9-]+)/$', views.v2),
    url(r'^$', views.index, name="index"),
    url(r'^modules/(?P<profile_name>[a-zA-Z0-9-]+)/(?P<region_name>[a-zA-Z0-9-]+)/$', views.modules, name='modules'),
    url(r'^edit_module_json/(?P<module_id>\d+)/$', views.edit_module_json, name='edit_module_json'),
    url(r'^updateplans/$', views.updateplans, name='updateplans'),
    url(r'^updateplan/(?P<plan_id>\d+)/$', views.updateplan, name='updateplan'),
    url(r'^updateplan/(?P<plan_id>\d+)/kickdevices/(?P<step_id>\d+)/$', views.kick_devices, name='kickdevices'),
    url(r'^new_updateplan/$', views.new_updateplan, name='new_updateplan'),
    url(r'^new_module/$', views.new_module, name='new_module'),
    url(r'^fix_service_types/$', views.fix_service_types, name='fix_service_types'),
    url(r'^instances_summary/(?P<plan_id>\d+)/$', views.instances_summary, name='instances_summary'),
    url(r'^elb_summary/(?P<plan_id>\d+)/$', views.elb_summary, name='elb_summary'),
    url(r'actionlogs/(?P<plan_id>\d+)/$', views.actionlogs, name='actionlogs'),
    url(r'^edit_module/(?P<module_id>\d+)/$', views.edit_module, name='edit_module'),

    # ajax views:
    url(r'ajax/run_module_ec2/', ajax_views.run_module_ec2, name='ajax.run_module_ec2'),
    url(r'ajax/add_module_ec2_tags/', ajax_views.add_module_ec2_tags, name='ajax.add_module_ec2_tags'),
    url(r'ajax/add_module_volume_tags/', ajax_views.add_module_volume_tags, name='ajax.add_module_volume_tags'),
    url(r'ajax/stop_module_ec2/', ajax_views.stop_module_ec2, name='ajax.stop_module_ec2'),
    url(r'ajax/stop_module_previous_ec2/', ajax_views.stop_module_previous_ec2, name='ajax.stop_module_previous_ec2'),
    url(r'ajax/reg_module_elb/', ajax_views.reg_module_elb, name='ajax.reg_module_ec2'),
    url(r'ajax/dereg_module_elb/', ajax_views.dereg_module_elb, name='ajax.dereg_module_ec2'),
    url(r'ajax/check_module_elb_health/', ajax_views.check_module_elb_health, name='ajax.check_module_elb_health'),
    url(r'ajax/disable_module_alarm/', ajax_views.disable_module_alarm, name='ajax.disable_module_alarm'),

    url(r'ajax/deregister_connectors/', ajax_views.deregister_connectors, name='ajax.deregister_connectors'),
    url(r'ajax/get_connector_device_numbers/', ajax_views.get_connector_device_numbers, name='ajax.get_connector_device_numbers'),
    url(r'ajax/init_connector_close_all/', ajax_views.init_connector_close_all, name='ajax.init_connector_close_all'),

    url(r'ajax/finish_step/', ajax_views.finish_step, name='ajax.finish_step'),

    url(r'api/new_updateplan/', api_views.new_updateplan, name='api.new_updateplan'),
]

PrdDeployer/updateplanmgr/views.py
import json
from datetime import datetime
import logging

from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import get_object_or_404, render
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.utils import timezone
from django.conf import settings
import pytz
import boto3
import requests

from awscredentialmgr.models import AWSProfile, AWSRegion
from awsresourcemgr.models import AWSResource, AWSResourceHandler
from ec2mgr.models import EC2Instance, Connector
from .models import Module, UpdatePlan, UpdateStep, UpdateActionLog
from boto3helper.ec2 import get_instances_by_filters, \
    get_instance_module_version
from boto3helper.tags import to_dict, get_name, get_resource_name

logger = logging.getLogger('common')


@login_required
def index(request):
    profiles = AWSProfile.objects.all()
    context = {
        'title': "Home",
        'profiles': profiles
    }
    return render(request, 'updateplanmgr/index_ace.html', context=context)


@login_required
def modules(request, profile_name, region_name):
    profile = get_object_or_404(AWSProfile, name=profile_name)
    region = get_object_or_404(AWSRegion, name=region_name)

    modules = Module.objects.filter(profile=profile, region=region)\
        .order_by("name", "-current_version")

    context = {
        'title': "Modules",
        'profile': profile,
        'region': region,
        'modules': modules
    }
    return render(request, 'updateplanmgr/modules_ace.html', context)


@login_required
def edit_module_json(request, module_id):
    module = Module.objects.get(pk=module_id)
    if request.method == "POST":
        action = request.POST.get('submit')
        if action == "Reset":
            return HttpResponseRedirect(reverse('updateplanmgr:edit_module_json', args=(module.id,)))
        elif action == "Cancel":
            return HttpResponseRedirect(reverse(
                'updateplanmgr:modules',
                kwargs={
                    'profile_name': module.profile.name,
                    'region_name': module.region.name
                }
            ))
        elif action == "Save":
            text = request.POST.get('json')
            try:
                obj = json.loads(text)
                module.configuration = json.dumps(obj, indent=2)
                module.save()
                return HttpResponseRedirect(reverse(
                    'updateplanmgr:modules',
                    kwargs={
                        'profile_name': module.profile.name,
                        'region_name': module.region.name
                    }
                ))
            except:
                context = {
                    'title': "Edit Module",
                    'message': 'Bad JSON text.',
                    'module': module,
                    'json': text
                }
                return render(request, 'updateplanmgr/edit_module_json_ace.html', context)
    else:
        context = {
            'title': "Edit Module",
            'module': module,
            'json': module.configuration
        }
        return render(request, 'updateplanmgr/edit_module_json_ace.html', context)


@login_required
def updateplans(request):
    plans = UpdatePlan.objects.all()
    context = {
        'title': "Update Plans",
        'plans': plans
    }
    return render(request, 'updateplanmgr/updateplans_ace.html', context)


@login_required
def updateplan(request, plan_id):
    plan = get_object_or_404(UpdatePlan, pk=plan_id)
    steps = plan.steps.order_by('sequence')

    time_steps = list()
    temp_datetime = None
    for step in steps:
        if temp_datetime is None or step.start_time != temp_datetime:
            time_steps.append({
                'start_time': step.start_time,
                'steps': [step,]
            })
            temp_datetime = step.start_time
        else:
            time_steps[-1]['steps'].append(step)


    context = {
        'title': "UpdatePlan",
        'plan': plan,
        'steps': steps,
        'time_steps': time_steps,
        'alarm_url': settings.OPENFALCON['alarm_url'],
    }
    return render(request, 'updateplanmgr/updateplan_ace.html', context)


def get_module_image(profile, region, module_name, version):
    """Get module AMI by module name and version"""
    image = AWSResource.objects.filter(
        profile=profile,
        region=region,
        resource_type="image",
        name__contains="-%s-%s-"%(module_name, version)
    ).order_by('-name').first()
    return image


def make_new_module(profile, region, module_name, version, \
    instance_count, configuration, service_type, load_balancer_names):
    """Create a brand new module"""
    # Check for AMI image:
    new_image = get_module_image(profile, region, module_name, version)
    if new_image is None:
        raise Exception("ImageNotFound: %s:%s, %s-%s"%(profile.name, region.name, module_name, version))
    # check for old module:
    query_set = Module.objects.filter(
        profile=profile,
        region=region,
        name=module_name
    )
    if query_set.exists():
        raise Exception("Module already exists: "+module_name)
    if type(configuration) == dict:
        configuration = json.dumps(configuration, indent=2)
    # create new module:
    module = Module(
        name=module_name,
        profile=profile,
        region=region,
        current_version=version,
        previous_version=version,
        is_online_version=True,
        instance_count=instance_count,
        configuration=configuration,
        service_type=service_type,
        load_balancer_names=load_balancer_names
    )
    module.save()
    return module


def make_new_version_module(profile, region, module_name, current_version, \
    new_version, instance_count=None, load_balancer_names=None):
    # check for new image:
    try:
        new_image = get_module_image(profile, region, module_name, new_version)
    except:
        raise Exception("ImageNotFound: %s:%s, %s-%s"%(profile.name, region.name, module_name, new_version))
    # check for old module:
    try:
        module_old = Module.objects.get(
            profile=profile,
            region=region,
            name=module_name,
            current_version=current_version
        )
    except:
        raise Exception(module_name+"-"+current_version+": OldModuleNotFound")
    # check if new version module already exists:
    try:
        module = Module.objects.get(
            profile=profile,
            region=region,
            name=module_name,
            current_version=new_version
        )
        # set new count when scaling out/in:
        if module.instance_count != instance_count and instance_count != 0 and instance_count is not None:
            module.instance_count = instance_count
        module.save()
        return module
    except:
        # create new module:
        ## copy unchanged info from old module:
        module = Module(
            name=module_old.name,
            profile=module_old.profile,
            region=module_old.region,
            current_version=new_version,
            previous_version=module_old.current_version,
            service_type=module_old.service_type
        )
        # edit new values:
        if instance_count is None:
            module.instance_count = module_old.instance_count
        elif instance_count == 0:
            module.instance_count = module_old.instance_count
        else:
            module.instance_count = instance_count
        if load_balancer_names is None:
            module.load_balancer_names = module_old.load_balancer_names
        else:
            module.load_balancer_names = load_balancer_names
        # set new image in module configuration:
        conf = json.loads(module_old.configuration)
        conf.update({
            'image':[new_image.name, new_image.resource_id]
        })
        module.configuration = json.dumps(conf, indent=2)
        module.save()
        return module

def make_update_step():
    pass

@login_required
def new_updateplan(request):
    """Create a new update plan"""
    if request.method =="POST":
        # record action log:
        actionlog = UpdateActionLog.create(
            request,
            action="new_updateplan"
        )
        # create plan:
        str_start_time = request.POST.get('start_time')
        tz = pytz.timezone(settings.TIME_ZONE)
        start_time = tz.localize(datetime.now())
        # try different formats of datetime:
        formats = (
            "%Y-%m-%d %H:%M:%S",
            "%Y%m%d%H%M%S",
            "%Y%m%d"
        )
        for fmt in formats:
            try:
                parsed_start_time = datetime.strptime(str_start_time, fmt)
                parsed_start_time = tz.localize(parsed_start_time)
                start_time = parsed_start_time
                break
            except:
                continue
        plan = UpdatePlan(
            project_name=request.POST.get('project_name'),
            project_code=request.POST.get('project_code'),
            project_leader=request.POST.get('project_leader'),
            note=request.POST.get('note'),
            start_time=start_time
        )
        plan.save()
        # update action log:
        actionlog.update_plan = plan
        actionlog.set_result(True)
        actionlog.save()
        # create each step and add to plan:
        stepCount = int(request.POST.get('stepCount'))
        for i in range(stepCount):
            profile_name = request.POST.get('profile['+str(i)+']')
            region_name = request.POST.get('region['+str(i)+']')
            instance_count = request.POST.get('numberOfInstances['+str(i)+']')
            try:
                instance_count = int(instance_count)
            except:
                instance_count = 0
            module = make_new_version_module(

PrdDeployer/updateplanmgr/templates/updateplanmgr/index_ace.html
{% extends 'layout.html' %}
{% block title %}Index{% endblock %}
{% block body %}

<div class="row">
    <a class="btn btn-primary btn-large no-border" href="{% url 'updateplanmgr:updateplans' %}">
        <i class="icon-list"></i>
        View All Update Plans
    </a>
    <a class="btn btn-danger btn-large no-border" href="{% url 'updateplanmgr:new_updateplan' %}">
        <i class="icon-plus"></i>
        New Update Plan
    </a>
</div>

{% for profile in profiles %}
<h3 class="header smaller">{{profile.name}}</h3>
<div class="row">
    {% for region in profile.regions.all %}
    <div class="widget col-sm-4">
        <div class="widget-header widget-header-flat">
            <h5 class="brown">{{region.name}}</h5>
        </div>
        <div class="widget-body">
            <div class="widget-main">
                <div>
                    <a href="{% url 'updateplanmgr:modules' profile_name=profile.name region_name=region.name %}">
                        <i class="icon-cog"></i>
                        Modules
                    </a>
                </div>
                <div>
                    <a href="{% url 'awsresourcemgr:resources' profile_name=profile.name region_name=region.name %}">
                        <i class="icon-file"></i>
                        Resources
                    </a>
                </div>
                <div>
                    <a href="{% url 'awsresourcemgr:update_resources' profile_name=profile.name region_name=region.name resource_type='all' %}">
                        <li class="icon-cloud-download"></li>
                        Update Resources
                    </a>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endfor %}

{% endblock %}

PrdDeployer/updateplanmgr/templates/updateplanmgr/updateplan_ace.html
{% extends 'layout.html' %}
{% block title %}UpdatePlan{% endblock %}
{% block body %}
<h3 class="header smaller" style="margin-top: 320px;">
    {{plan.project_name}}
    <small>
        <i class="icon-double-angle-right"></i>
        {{plan.project_code}} -- {{plan.project_leader}}
    </small>
</h3>
<p>
    <a class="btn btn-sm btn-info no-border" href="{% url 'updateplanmgr:instances_summary' plan_id=plan.id %}" target="_blank">
        <i class="icon-desktop"></i>
        Check EC2 Status
    </a>
    <a class="btn btn-sm btn-info no-border" href="{% url 'updateplanmgr:elb_summary' plan_id=plan.id %}" target="_blank">
        <i class="icon-random"></i>
        Check ELB Status
    </a>
    <a class="btn btn-sm btn-info no-border" href="{% url 'updateplanmgr:actionlogs' plan_id=plan.id %}" target="_blank">
        <i class="icon-list"></i>
        View Action Logs
    </a>
    <a class="btn btn-sm btn-info no-border" href="{{alarm_url}}" target="_blank">
        <i class="icon-bell"></i>
        Open Alarm Page
    </a>
    <a class="btn btn-sm btn-success no-border" style="float:right;" onclick="window.location.reload()">
        <i class="icon-refresh"></i>
        Refresh
    </a>
</p>

<table class="table table-striped table-bordered table-hover">
    <thead>
        <tr>
            <th>Step</th>
            <th>Region</th>
            <th>Module</th>
            <!--<th>New Version</th>-->
            <th>New EC2</th>
            <th>Old Version</th>
            <th>Old EC2</th>
            <th>ELB</th>
            <!--<th>ELB State</th>-->
            <th>ELB Actions</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        {% for step in steps %}
        <tr>
            <td>{{step.sequence}}</td>
            <td>{{step.module.region.full_name}}</td>
            <td>{{step.module.display_name}}</td>
            <!--<td>{{step.module.current_version}}</td>-->
            <td>
                <button class="btn btn-xs no-border btn-primary" onclick="run_module_ec2({{step.id}})">Run</button>
                <span>{{step.module.healthy_instance_count}}/{{step.module.instance_count}}</span>
            </td>
            <td>
                <button class="btn btn-xs no-border btn-inverse" onclick="disable_module_alarm({{step.id}})">
                    <i class="icon-bell"></i>
                    Disable Alarm
                </button>
                {{step.module.previous_version}}
            </td>
            <td>
                <button class="btn btn-xs no-border btn-danger" onclick="stop_module_previous_ec2({{step.id}})">Stop</button>
                <span>{{step.module.previous_module.healthy_instance_count}}/{{step.module.previous_module.instance_count}}</span>
            </td>
            <td>{{step.module.load_balancer_names}}</td>
            <!--<td>
                <span id="spanElbState"></span>
                <button class="btn btn-xs no-border btn-info" onclick="check_module_elb_health({{step.id}})">Check</button>
            </td>-->
            <td>
                {% if step.module.load_balancer_names %}
                <button class="btn btn-xs no-border btn-primary" onclick="reg_module_elb({{step.id}})">Reg. New</button>
                <button class="btn btn-xs no-border btn-danger" onclick="dereg_module_elb({{step.id}})">Dereg. Old</button>
                {% endif %}
            </td>
            <td>
                <!--<button class="btn btn-xs no-border btn-info" onclick="finish_step({{step.id}})">Mark</button>-->
                <!--<a target="_blank" href="{% url 'updateplanmgr:edit_module_json' step.module.id %}">Edit JSON</a>-->
                <a style="font-size:1.5em" target="_blank" href="{% url 'updateplanmgr:edit_module' step.module.id %}" title="Edit Module"><i class="icon-edit"></i></a>
                <a style="font-size:1.5em" target="_blank" href="./kickdevices/{{ step.id }}/" title="Kick Devices"><i class="icon-bolt"></i></a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<div class="widget-box" style="position: fixed; top: 50px; width: 85%;">
    <div class="widget-header widget-header-flat widget-header-small">
        <h5>Action Log</h5>
    </div>
    <div class="widget-body">
        <div class="widget-main">
            <div style="min-height:300px; height: 300px; overflow:auto;" id="divAjaxMessage"></div>
        </div>
    </div>
</div>

{% endblock %}
{% block page_js %}
<script type="text/javascript">
function run_module_ec2(step_id) {
    if (!confirm("Run new instances?")) return;
    show_ajax_action("Launching EC2 instances ...");
    $.ajax({
        url: '/prdbsxt/update/ajax/run_module_ec2/',
        method: 'post',
        dataType: 'json',
        data: {
            step_id: step_id
        },
        success: function(instance_ids) {
            show_ajax_action(JSON.stringify(instance_ids));
            console.log(instance_ids);
            add_module_ec2_tags(step_id, instance_ids);
        },
        error: function(jqXHR, textStatus, errorThrown) {
            show_ajax_error(jqXHR, textStatus, errorThrown);
        }
    });
}

function add_module_ec2_tags(step_id, instance_ids) {
    if (instance_ids.length == 0)
        return;
    show_ajax_action("Adding tags to EC2 instances ...");
    $.ajax({
        url: '/prdbsxt/update/ajax/add_module_ec2_tags/',
        method: 'post',
        dataType: 'json',
        data: {
            step_id: step_id,
            instance_ids: instance_ids
        },
        success: function(data) {
            show_ajax_action(JSON.stringify(data));
            console.log(data);
            add_module_volume_tags(step_id, instance_ids);
        },
        error: function(jqXHR, textStatus, errorThrown) {
            show_ajax_error(jqXHR, textStatus, errorThrown);
        }
    });
}

function add_module_volume_tags(step_id, instance_ids) {
    if (instance_ids.length == 0)
        return;
    show_ajax_action("Adding tags to EBS volumes ...");
    $.ajax({
        url: '/prdbsxt/update/ajax/add_module_volume_tags/',
        method: 'post',
        dataType: 'json',
        data: {
            step_id: step_id,
            instance_ids: instance_ids
        },
        success: function(data) {
            show_ajax_action(JSON.stringify(data));
            console.log(data);
        },
        error: function(jqXHR, textStatus, errorThrown) {
            show_ajax_error(jqXHR, textStatus, errorThrown);
        }
    })
}


function stop_module_ec2(step_id) {
    if (!confirm("Stop these instances?")) return;
    show_ajax_action("Marking instances as 'to_stop' ...");
    $.ajax({
        url: '/prdbsxt/update/ajax/stop_module_ec2/',
        method: 'post',
        dataType: 'json',
        data: {
            step_id: step_id
        },
        success: function(data) {
            show_ajax_action(JSON.stringify(data));
            console.log(data);
        },
        error: function(jqXHR, textStatus, errorThrown) {
            show_ajax_error(jqXHR, textStatus, errorThrown);
        }
    })
}


function stop_module_previous_ec2(step_id) {
    if (!confirm("Stop old instances?")) return;
    show_ajax_action("Stopping ... Use [Check EC2 Status] to see latest status.");
    $.ajax({
        url: '/prdbsxt/update/ajax/stop_module_previous_ec2/',
        method: 'post',
        dataType: 'json',
        data: {
            step_id: step_id
        },
        success: function(data) {
            show_ajax_action(JSON.stringify(data));
            console.log(data);
        },
        error: function(jqXHR, textStatus, errorThrown) {
            show_ajax_error(jqXHR, textStatus, errorThrown);
        }
    })
}


function reg_module_elb(step_id) {
    if (!confirm("Register new instances?")) return;
    show_ajax_action("Registering instances with load balancers ...");
    $.ajax({
        url: '/prdbsxt/update/ajax/reg_module_elb/',
        method: 'post',
        dataType: 'json',
        data: {
            step_id: step_id
        },
        success: function(data) {
            show_ajax_action(JSON.stringify(data));
            console.log(data);
        },
        error: function(jqXHR, textStatus, errorThrown) {
            show_ajax_error(jqXHR, textStatus, errorThrown);
        }
    })
}


function dereg_module_elb(step_id) {
    if (!confirm("Deregister old instances?")) return;
    show_ajax_action("Deregistering instances from load balancers ...");
    $.ajax({
        url: '/prdbsxt/update/ajax/dereg_module_elb/',
        method: 'post',
        dataType: 'json',
        data: {
            step_id: step_id
        },
        success: function(data) {
            show_ajax_action(JSON.stringify(data));
            console.log(data);
        },
        error: function(jqXHR, textStatus, errorThrown) {
            show_ajax_error(jqXHR, textStatus, errorThrown);
        }
    })
}


function finish_step(step_id) {
    if (!confirm("Finish this step?")) return;
    show_ajax_action("Finishing step ...");
    $.ajax({
        url: '/prdbsxt/update/ajax/finish_step/',
        method: 'post',
        dataType: 'json',
        data: {
            step_id: step_id
        },
        success: function(result) {
            show_ajax_action(JSON.stringify(result));
            if (result[0]) {
                alert("Step finished.")
                // TODO disable buttons here
            } else {
                alert("Cannot finish step: "+result[1])
            }
        },
        error: function(jqXHR, textStatus, errorThrown) {
            show_ajax_error(jqXHR, textStatus, errorThrown);
        }
    })
}


function check_module_elb_health(step_id) {
    $.ajax({
        url: "/prdbsxt/update/ajax/check_module_elb_health/",
        method: "post",
        dataType: "json",
        data: {
            step_id: step_id
        },
        success: function(data) {
            show_ajax_action(JSON.stringify(data));
            if (data) {
                $('#spanElbState').html(
                    data[0]+"/"+data[1]+" InService"
                );
            }
        },
        error: function(jqXHR, textStatus, errorThrown) {
            show_ajax_error(jqXHR, textStatus, errorThrown);
        }
    })
}


function disable_module_alarm(step_id) {
    $.ajax({
        url: "/prdbsxt/update/ajax/disable_module_alarm/",
        method: "post",
        dataType: "json",
        data: {
            step_id: step_id
        },
        success: function(result) {
            show_ajax_action(JSON.stringify(result));
            var message = "Notice: OpenFalcon returns '200 OK' no matter the result. Use the alarm page to make sure alarms are disabled.";
            show_ajax_action(message);
        },
        error: function(jqXHR, textStatus, errorThrown) {
            show_ajax_error(jqXHR, textStatus, errorThrown);
        }
    })
}


function show_ajax_action(msg) {
    var p = $("<p></p>").html(msg).addClass("body");
    var d = new Date()
    var divTimestamp = $("<div style='font-style: italic; background-color: #EFEFEF'></div>").html(d.toString());
    p.prependTo("#divAjaxMessage");
    divTimestamp.prependTo("#divAjaxMessage");
}


function show_ajax_error(xmlhttprequest, textstatus, message) {
    console.log(message);
    var divStatus = $("<div></div>").html("AJAX ERROR: "+textstatus);
    var divMessage = $("<div></div>").html("Error message: "+xmlhttprequest.responseJSON['message']);
    var d = new Date()
    var divTimestamp = $("<div></div>").html(d.toString());
    var p = $("<p></p>").addClass("body red");
    p.append(divTimestamp);
    p.append(divStatus);
    p.append(divMessage);
    p.prependTo("#divAjaxMessage");

}

$(document).on("keypress", 'form', function (e) {
    var code = e.keyCode || e.which;
    if (code == 13) {
        e.preventDefault();
        return false;
    }
});
</script>
{% endblock %}

PrdDeployer/updateplanmgr/templates/updateplanmgr/updateplans.html
{% extends 'base.html' %}
{% block title %}Update Plans{% endblock %}
{% block body %}
{% for plan in plans %}
<h3>{{plan.project_code}}</h3>
<ul>
    <li>Project: <a href="{% url 'updateplanmgr:updateplan' plan_id=plan.id%}">{{plan.project_name}}</a></li>
    <li>Leader: {{plan.project_leader}}</li>
</ul>
{% endfor %}
{% endblock %}