PrdDeployer/PrdDeployer/urls.py
"""
Definition of urls for PrdDeployer.
"""

from django.conf.urls import include, url
from django.http import HttpResponseRedirect

import updateplanmgr.urls
import awsresourcemgr.urls
import ec2mgr.urls

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from django.contrib.auth.views import login, logout
admin.autodiscover()

urlpatterns = [
    # Examples:
    # url(r'^$', 'PrdDeployer.views.home', name='home'),
    # url(r'^PrdDeployer/', include('PrdDeployer.PrdDeployer.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^prdbsxt/admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^prdbsxt/admin/', include(admin.site.urls)),

    # updateplanmgr
    url(r'^prdbsxt/update/', include(updateplanmgr.urls, namespace='updateplanmgr', app_name='updateplanmgr')),
    # awsresourcemgr:
    url(r'^prdbsxt/awsres/', include(awsresourcemgr.urls, namespace='awsresourcemgr', app_name='awsresourcemgr')),
    # ec2mgr:
    url(r'^prdbsxt/ec2/', include(ec2mgr.urls, namespace='ec2mgr', app_name='ec2mgr')),

    url(r'^prdbsxt/accounts/login/', login,
        {'template_name': 'admin/login.html'}),
    url(r'^prdbsxt/accounts/logout/', logout, name='logout'),

    # Redirect any other requests to home page:
    url(r'^prdbsxt/$', lambda r: HttpResponseRedirect('update/'), name="home"),
    url(r'^$', lambda r: HttpResponseRedirect('prdbsxt/update/'), name="home"),
    #url(r'^/$', lambda r: HttpResponseRedirect('prdbsxt/update/'), name="home"),
]

PrdDeployer/ec2mgr/urls.py
from django.conf.urls import include, url

from ec2mgr import views

urlpatterns = [
    url(r'^sync/(?P<profile_name>[a-zA-Z0-9-]+)/(?P<region_name>[a-zA-Z0-9-]+)/$', views.sync_instances_ex, name="sync_instances_ex"),
    url(r'instances/', views.instances, name="instances"),
    url(r'retired/', views.retired_instances, name='retired_instances'),
]

PrdDeployer/updateplanmgr/urls.py
from django.conf.urls import include, url

from updateplanmgr import views
from updateplanmgr import ajax_views
from updateplanmgr import api_views

urlpatterns = [
    #url(r'^v1/$', views.v1),
    #url(r'^v2/(?P<profile_name>[a-zA-Z0-9-]+)/(?P<region_name>[a-zA-Z0-9-]+)/$', views.v2),
    url(r'^$', views.index, name="index"),
    url(r'^modules/(?P<profile_name>[a-zA-Z0-9-]+)/(?P<region_name>[a-zA-Z0-9-]+)/$', views.modules, name='modules'),
    url(r'^edit_module_json/(?P<module_id>\d+)/$', views.edit_module_json, name='edit_module_json'),
    url(r'^updateplans/$', views.updateplans, name='updateplans'),
    url(r'^updateplan/(?P<plan_id>\d+)/$', views.updateplan, name='updateplan'),
    url(r'^updateplan/(?P<plan_id>\d+)/kickdevices/(?P<step_id>\d+)/$', views.kick_devices, name='kickdevices'),
    url(r'^new_updateplan/$', views.new_updateplan, name='new_updateplan'),
    url(r'^new_module/$', views.new_module, name='new_module'),
    url(r'^fix_service_types/$', views.fix_service_types, name='fix_service_types'),
    url(r'^instances_summary/(?P<plan_id>\d+)/$', views.instances_summary, name='instances_summary'),
    url(r'^elb_summary/(?P<plan_id>\d+)/$', views.elb_summary, name='elb_summary'),
    url(r'actionlogs/(?P<plan_id>\d+)/$', views.actionlogs, name='actionlogs'),
    url(r'^edit_module/(?P<module_id>\d+)/$', views.edit_module, name='edit_module'),

    # ajax views:
    url(r'ajax/run_module_ec2/', ajax_views.run_module_ec2, name='ajax.run_module_ec2'),
    url(r'ajax/add_module_ec2_tags/', ajax_views.add_module_ec2_tags, name='ajax.add_module_ec2_tags'),
    url(r'ajax/add_module_volume_tags/', ajax_views.add_module_volume_tags, name='ajax.add_module_volume_tags'),
    url(r'ajax/stop_module_ec2/', ajax_views.stop_module_ec2, name='ajax.stop_module_ec2'),
    url(r'ajax/stop_module_previous_ec2/', ajax_views.stop_module_previous_ec2, name='ajax.stop_module_previous_ec2'),
    url(r'ajax/reg_module_elb/', ajax_views.reg_module_elb, name='ajax.reg_module_ec2'),
    url(r'ajax/dereg_module_elb/', ajax_views.dereg_module_elb, name='ajax.dereg_module_ec2'),
    url(r'ajax/check_module_elb_health/', ajax_views.check_module_elb_health, name='ajax.check_module_elb_health'),
    url(r'ajax/disable_module_alarm/', ajax_views.disable_module_alarm, name='ajax.disable_module_alarm'),

    url(r'ajax/deregister_connectors/', ajax_views.deregister_connectors, name='ajax.deregister_connectors'),
    url(r'ajax/get_connector_device_numbers/', ajax_views.get_connector_device_numbers, name='ajax.get_connector_device_numbers'),
    url(r'ajax/init_connector_close_all/', ajax_views.init_connector_close_all, name='ajax.init_connector_close_all'),

    url(r'ajax/finish_step/', ajax_views.finish_step, name='ajax.finish_step'),

    url(r'api/new_updateplan/', api_views.new_updateplan, name='api.new_updateplan'),
]

PrdDeployer/PrdDeployer/templates/base.html
<!DOCTYPE html>{% load staticfiles %}
<html>
    <head>
        <meta charset="utf-8" />
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" type="text/css" href="{% static "css/common.css" %}" charset="utf-8" />
    </head>
    <body>
        <div>
            <a href="{% url 'updateplanmgr:index' %}">Home</a>
        </div>
        {% block body %}{% endblock %}
        <script type="text/javascript" src="{% static 'js/jquery.js' %}" charset="utf-8"></script>   
        <!-- SETUP JQUERY CSRF_TOKEN -->
        <script type="text/javascript">
function handleAjaxError(xhr, status, error) {
    alert("Ajax request failed: "+status+" \n "+error)
}

// using jQuery
function getCookie(name) {
    var cookieValue = null;
    if (document.cookie && document.cookie !== '') {
        var cookies = document.cookie.split(';');
        for (var i = 0; i < cookies.length; i++) {
            var cookie = jQuery.trim(cookies[i]);
            // Does this cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) === (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
}
function csrfSafeMethod(method) {
    // these HTTP methods do not require CSRF protection
    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
}

var csrftoken = getCookie('csrftoken');
$.ajaxSetup({
    beforeSend: function(xhr, settings) {
        if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
            xhr.setRequestHeader("X-CSRFToken", csrftoken);
        }
    },
    error: handleAjaxError
});
        </script>
        {% block page_js %}{% endblock %}
    </body>
</html>

PrdDeployer/PrdDeployer/templates/layout.html
<!DOCTYPE html>
<html lang="en">
    {% load staticfiles %}
	<head>
		<meta charset="utf-8" />
		<title>PrdDeployer - {{title}}</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<!-- basic styles -->
		<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" />
		<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" />

		<!--[if IE 7]>
		  <link rel="stylesheet" href="{% static 'css/font-awesome-ie7.min.css' %}" />
		<![endif]-->

		<!-- page specific plugin styles -->

		<!-- fonts -->



		<!-- ace styles -->

		<link rel="stylesheet" href="{% static 'css/ace.min.css' %}" />
		<link rel="stylesheet" href="{% static 'css/ace-rtl.min.css' %}" />
		<link rel="stylesheet" href="{% static 'css/ace-skins.min.css' %}" />

		<!--[if lte IE 8]>
		  <link rel="stylesheet" href="{% static 'css/ace-ie.min.css' %}" />
		<![endif]-->

		<link rel="stylesheet" href="{% static 'css/common.css' %}" />

		<!-- inline styles related to this page -->

		<!-- ace settings handler -->

		<script src="{% static 'js/ace-extra.min.js' %}"></script>

		<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->

		<!--[if lt IE 9]>
		<script src="{% static 'js/html5shiv.js' %}"></script>
		<script src="{% static 'js/respond.min.js' %}"></script>
		<![endif]-->
	</head>

	<body>
		<div class="navbar navbar-default" id="navbar">
			<script type="text/javascript">
				try{ace.settings.check('navbar' , 'fixed')}catch(e){}
			</script>

			<div class="navbar-container" id="navbar-container">
				<div class="navbar-header pull-left">
					<a href="#" class="navbar-brand">
						<small>
							<i class="icon-arrow-up"></i>
							PRD-DEPLOYER
						</small>
					</a><!-- /.brand -->
				</div><!-- /.navbar-header -->

				<div class="navbar-header pull-right" role="navigation">
					<ul class="nav ace-nav">

						<li class="light-blue">
							<a data-toggle="dropdown" href="#" class="dropdown-toggle">
								<img class="nav-user-photo" src="{% static 'avatars/avatar2.png' %}" alt="{{user.get_username}}" />
								<span class="user-info">
                                    <small>User Role</small>
                                    {{user.get_username}}
								</span>

								<i class="icon-caret-down"></i>
							</a>

							<ul class="user-menu pull-right dropdown-menu dropdown-yellow dropdown-caret dropdown-close">
								<li>
									<a href="/prdbsxt/admin/">
										<i class="icon-cog"></i>
										Administration
									</a>
								</li>

								<!--<li>
									<a href="#">
										<i class="icon-user"></i>
										Profile
									</a>
								</li> -->

								<li class="divider"></li>

								<li>
									<a href="{% url 'logout' %}">
										<i class="icon-off"></i>
										Log Out
									</a>
								</li>
							</ul>
						</li>
					</ul><!-- /.ace-nav -->
				</div><!-- /.navbar-header -->
			</div><!-- /.container -->
		</div>

		<div class="main-container" id="main-container">
			<script type="text/javascript">
				try{ace.settings.check('main-container' , 'fixed')}catch(e){}
			</script>

			<div class="main-container-inner">
				<a class="menu-toggler" id="menu-toggler" href="#">
					<span class="menu-text"></span>
				</a>

				<div class="sidebar" id="sidebar">
					<script type="text/javascript">
						try{ace.settings.check('sidebar' , 'fixed')}catch(e){}
					</script>

					<ul class="nav nav-list">
						<li class="active">
							<a href="{% url 'updateplanmgr:index' %}">
								<i class="icon-home"></i>
								<span class="menu-text"> Home </span>
							</a>
						</li>
						<li>
							<a href="{% url 'updateplanmgr:new_updateplan' %}">
								<i class="icon-plus"></i>
								<span class="menu-text"> New Plan </span>
							</a>
                        </li>
                        <li>
							<a href="{% url 'updateplanmgr:updateplans' %}">
								<i class="icon-list"></i>
								<span class="menu-text"> Update Plans </span>
							</a>
						</li>
						<li>
							<a href="{% url 'ec2mgr:retired_instances' %}">
								<i class="icon-desktop"></i>
								<span class="menu-text"> Retired Instances </span>
							</a>
                        </li>
                        <!--<li>
							<a href="{% url 'updateplanmgr:index' %}">
								<i class="icon-cog"></i>
								<span class="menu-text"> Modules </span>
							</a>
                        </li>
                        <li>
							<a href="{% url 'updateplanmgr:index' %}">
								<i class="icon-file"></i>
								<span class="menu-text"> Resources </span>
							</a>
                        </li>
					</ul>--><!-- /.nav-list -->


					<script type="text/javascript">
						try{ace.settings.check('sidebar' , 'collapsed')}catch(e){}
					</script>
				</div>

				<div class="main-content">

					<div class="page-content">
						<div class="page-header">
							<h1>{{title}}</h1>
						</div><!-- /.page-header -->

						<div class="row">
							<div class="col-xs-12">
								<!-- PAGE CONTENT BEGINS -->
                                {% comment %}
                                INSERT PAGE CONTENT HERE
                                {% endcomment %}
                                {% block body %}{% endblock %}
								<!-- PAGE CONTENT ENDS -->
							</div><!-- /.col -->
						</div><!-- /.row -->
					</div><!-- /.page-content -->
				</div><!-- /.main-content -->

			</div><!-- /.main-container-inner -->

			<a href="#" id="btn-scroll-up" class="btn-scroll-up btn btn-sm btn-inverse">
				<i class="icon-double-angle-up icon-only bigger-110"></i>
			</a>
		</div><!-- /.main-container -->

		<!-- basic scripts -->

		<!--[if !IE]> -->

		<script src="{% static 'js/jquery-2.0.3.min.js' %}"></script>
		<script src="{% static 'js/jquery-ui-1.10.3.full.min.js' %}"></script>

		<!-- <![endif]-->

		<!--[if IE]>
<script src="{% static 'js/jquery-1.10.2.min.js' %}"></script>
<![endif]-->

		<!--[if !IE]> -->

		<script type="text/javascript">
			window.jQuery || document.write("<script src='{% static 'js/jquery-2.0.3.min.js' %}'>"+"<"+"script>");
		</script>

		<!-- <![endif]-->

		<!--[if IE]>
<script type="text/javascript">
 window.jQuery || document.write("<script src='{% static 'js/jquery-1.10.2.min.js' %}'>"+"<"+"script>");
</script>
<![endif]-->

		<script src="{% static 'js/bootstrap.min.js' %}"></script>
		<script src="{% static 'js/typeahead-bs2.min.js' %}"></script>

		<!-- page specific plugin scripts -->

		<!--[if lte IE 8]>
		  <script src="{% static 'js/excanvas.min.js' %}"></script>
		<![endif]-->

		<script src="{% static 'js/jquery-ui-1.10.3.custom.min.js' %}"></script>
		<script src="{% static 'js/jquery.slimscroll.min.js' %}"></script>
		<script src="{% static 'js/jquery.easy-pie-chart.min.js' %}"></script>
		<script src="{% static 'js/jquery.sparkline.min.js' %}"></script>
		<script src="{% static 'js/flot/jquery.flot.min.js' %}"></script>
		<script src="{% static 'js/flot/jquery.flot.pie.min.js' %}"></script>
		<script src="{% static 'js/flot/jquery.flot.resize.min.js' %}"></script>
		<script src="{% static 'js/bootbox.min.js' %}"></script>

		<!-- ace scripts -->

		<script src="{% static 'js/ace-elements.min.js' %}"></script>
		<script src="{% static 'js/ace.min.js' %}"></script>

		{% block additional_js_files %}{% endblock %}
		<!-- inline scripts related to this page -->

		<script type="text/javascript">
function handleAjaxError(xhr, status, error) {
        alert("Ajax request failed: "+status+" \n "+error)
}

function getCookie(name) {
    var cookieValue = null;
    if (document.cookie && document.cookie !== '') {
        var cookies = document.cookie.split(';');
        for (var i = 0; i < cookies.length; i++) {
            var cookie = jQuery.trim(cookies[i]);
            // Does this cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) === (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
}
function csrfSafeMethod(method) {
    // these HTTP methods do not require CSRF protection
    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
}

var csrftoken = getCookie('csrftoken');
$.ajaxSetup({
    beforeSend: function(xhr, settings) {
        if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
            xhr.setRequestHeader("X-CSRFToken", csrftoken);
        }
    },
    error: handleAjaxError
});

$('[data-rel=popover]').popover({html:true});
		</script>
{% block page_js %}{% endblock %}
</body>
</html>